// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StajTakipUygulaması.Data;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(StajContext))]
    partial class StajContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StajTakipUygulaması.Domain.Entities.Basvuru", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BaslamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BaslamaYili")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BasvuruTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bolum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departman")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fakulte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgrenciNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RedNedeni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RedTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sinif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SorumluID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StajTuruID")
                        .HasColumnType("int");

                    b.Property<string>("TCKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Universite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yetkiler")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("StajTuruID");

                    b.ToTable("Basvurular");
                });

            modelBuilder.Entity("StajTakipUygulaması.Domain.Entities.BasvuruBelge", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Açıklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BasvuruID")
                        .HasColumnType("int");

                    b.Property<string>("BelgeAdı")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BelgeTipiID")
                        .HasColumnType("int");

                    b.Property<string>("Yolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BasvuruID");

                    b.HasIndex("BelgeTipiID");

                    b.ToTable("BasvuruBelgeleri");
                });

            modelBuilder.Entity("StajTakipUygulaması.Domain.Entities.Belge", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Açıklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BelgeAdı")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BelgeTipiID")
                        .HasColumnType("int");

                    b.Property<int>("StajID")
                        .HasColumnType("int");

                    b.Property<string>("Yolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BelgeTipiID");

                    b.HasIndex("StajID");

                    b.ToTable("Belgeler");
                });

            modelBuilder.Entity("StajTakipUygulaması.Domain.Entities.BelgeTipi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BelgeTipleri");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Ad = "Öğrenci Belgesi"
                        },
                        new
                        {
                            ID = 2,
                            Ad = "Transkript"
                        },
                        new
                        {
                            ID = 3,
                            Ad = "Staj Başvuru Formu"
                        },
                        new
                        {
                            ID = 4,
                            Ad = "Bilgi Taahütnamesi"
                        },
                        new
                        {
                            ID = 5,
                            Ad = "Referans Mektubu"
                        },
                        new
                        {
                            ID = 6,
                            Ad = "Staj Onay Raporu"
                        },
                        new
                        {
                            ID = 7,
                            Ad = "Detaylı Staj Durum Raporu"
                        },
                        new
                        {
                            ID = 8,
                            Ad = "Verilen_Referans Mektubu"
                        });
                });

            modelBuilder.Entity("StajTakipUygulaması.Domain.Entities.Staj", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("BaslamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Departman")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SorumluID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StajTuruID")
                        .HasColumnType("int");

                    b.Property<int>("StajyerID")
                        .HasColumnType("int");

                    b.Property<string>("Yetkiler")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("StajTuruID");

                    b.HasIndex("StajyerID");

                    b.ToTable("Stajlar");
                });

            modelBuilder.Entity("StajTakipUygulaması.Domain.Entities.StajTuru", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("StajTurleri");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Ad = "Zorunlu"
                        },
                        new
                        {
                            ID = 2,
                            Ad = "İŞKUR"
                        },
                        new
                        {
                            ID = 3,
                            Ad = "Kısmi Zamanlı"
                        },
                        new
                        {
                            ID = 4,
                            Ad = "İşletmede Mesleki Eğitim"
                        });
                });

            modelBuilder.Entity("StajTakipUygulaması.Domain.Entities.Stajyer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BaslamaYili")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bolum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fakulte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgrenciNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PAU_ogrencisi_mi")
                        .HasColumnType("bit");

                    b.Property<string>("Sinif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Universite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Stajyerler");
                });

            modelBuilder.Entity("StajTakipUygulaması.Domain.Entities.Basvuru", b =>
                {
                    b.HasOne("StajTakipUygulaması.Domain.Entities.StajTuru", "StajTuru")
                        .WithMany()
                        .HasForeignKey("StajTuruID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StajTuru");
                });

            modelBuilder.Entity("StajTakipUygulaması.Domain.Entities.BasvuruBelge", b =>
                {
                    b.HasOne("StajTakipUygulaması.Domain.Entities.Basvuru", "Basvuru")
                        .WithMany("BasvuruBelgeleri")
                        .HasForeignKey("BasvuruID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StajTakipUygulaması.Domain.Entities.BelgeTipi", "BelgeTipi")
                        .WithMany()
                        .HasForeignKey("BelgeTipiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basvuru");

                    b.Navigation("BelgeTipi");
                });

            modelBuilder.Entity("StajTakipUygulaması.Domain.Entities.Belge", b =>
                {
                    b.HasOne("StajTakipUygulaması.Domain.Entities.BelgeTipi", "BelgeTipi")
                        .WithMany("Belgeler")
                        .HasForeignKey("BelgeTipiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StajTakipUygulaması.Domain.Entities.Staj", "Staj")
                        .WithMany("Belgeler")
                        .HasForeignKey("StajID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BelgeTipi");

                    b.Navigation("Staj");
                });

            modelBuilder.Entity("StajTakipUygulaması.Domain.Entities.Staj", b =>
                {
                    b.HasOne("StajTakipUygulaması.Domain.Entities.StajTuru", "StajTuru")
                        .WithMany("Stajlar")
                        .HasForeignKey("StajTuruID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StajTakipUygulaması.Domain.Entities.Stajyer", "Stajyer")
                        .WithMany("Stajlar")
                        .HasForeignKey("StajyerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StajTuru");

                    b.Navigation("Stajyer");
                });

            modelBuilder.Entity("StajTakipUygulaması.Domain.Entities.Basvuru", b =>
                {
                    b.Navigation("BasvuruBelgeleri");
                });

            modelBuilder.Entity("StajTakipUygulaması.Domain.Entities.BelgeTipi", b =>
                {
                    b.Navigation("Belgeler");
                });

            modelBuilder.Entity("StajTakipUygulaması.Domain.Entities.Staj", b =>
                {
                    b.Navigation("Belgeler");
                });

            modelBuilder.Entity("StajTakipUygulaması.Domain.Entities.StajTuru", b =>
                {
                    b.Navigation("Stajlar");
                });

            modelBuilder.Entity("StajTakipUygulaması.Domain.Entities.Stajyer", b =>
                {
                    b.Navigation("Stajlar");
                });
#pragma warning restore 612, 618
        }
    }
}
